AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  play-with-cognito

  Sample SAM Template for play-with-cognito

Globals:
  Function:
    Timeout: 10

Resources:
  # ユーザプール(認証部分)の定義
  # Ref: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html
  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-user-pool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: name
          Required: true
        - AttributeDataType: String
          Name: comment
          Mutable: true
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  # ユーザプールクライアントの定義
  # Ref: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html
  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${AWS::StackName}-client-app
      UserPoolId: !Ref MyCognitoUserPool
      GenerateSecret: false

Outputs:
  # ユーザプールのIDを出力
  UserPoolId:
    Value: !Ref MyCognitoUserPool
    Export:
      Name: !Sub ${AWS::StackName}-user-pool-id

  # ユーザプールクライアントのIDを出力
  UserPoolClientId:
    Value: !Ref MyCognitoUserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-user-pool-client-id
