name: Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - issues/*
  pull_request:
    branches:
      - main
      - develop
      - issues/*

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: './node_modules/'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('./yarn.lock') }}
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: |
          echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
          yarn install
      - name: Lint
        run: yarn lint:check
      - name: Test
        run: yarn test
      - name: Vulnerability check
        run: yarn audit
